In [ ]:
import sys

# 1. Install Libraries

In [ ]:
#Install Libraries
conda install pandas numpy

# 02. Importing Libraries

In [3]:
#Import Libraries
import pandas as pd
import numpy as np

# 03. Create a Dataset

In [7]:
#Create a dataframe
animal_data = pd.DataFrame({"Animal Name": ['Monkey', 'Giraffe', 'Tiger', 'Penguin', 'Panda'],
                            "Favorite Foods": ['Bananas', 'Leaves', 'Deer', 'Fish', 'Bamboo'],
                            "Country": ['Egypt','Kenya', 'Russia', 'New Zealand', 'China'],
                            "Age": [ 2, 7, 3, 4, 5]})

In [9]:
animal_data.head(5)

  Animal Name Favorite Foods      Country  Age
0      Monkey        Bananas        Egypt    2
1     Giraffe         Leaves        Kenya    7
2       Tiger           Deer       Russia    3
3     Penguin           Fish  New Zealand    4
4       Panda         Bamboo        China    5

# 04. Use Apply() & Lambda() Functions

In [12]:
#Create a Triple Age function
def triple_age(row) : 
    return row['Age'] * 3

In [14]:
#Apply the funtion to the column and save the values in a new column (deriving a variable)
animal_data['triple_Age'] = animal_data.apply(triple_age, axis =1)

In [16]:
#Check the data
animal_data

  Animal Name Favorite Foods      Country  Age  triple_Age
0      Monkey        Bananas        Egypt    2           6
1     Giraffe         Leaves        Kenya    7          21
2       Tiger           Deer       Russia    3           9
3     Penguin           Fish  New Zealand    4          12
4       Panda         Bamboo        China    5          15

In [18]:
#Use Lambda Funstions animal_data
triple_Age_2 = lambda x:(x) * 3

In [20]:
triple_Age_2

In [22]:
#Check the column
triple_Age_2(animal_data['Age'])

0     6
1    21
2     9
3    12
4    15
Name: Age, dtype: int64

In [24]:
#Use the lambda funtion and save the values in a new column (deriving a variable)
animal_data['triple_Age_2'] = triple_Age_2(animal_data['Age'])

In [26]:
#Check the data
animal_data

  Animal Name Favorite Foods      Country  Age  triple_Age  triple_Age_2
0      Monkey        Bananas        Egypt    2           6             6
1     Giraffe         Leaves        Kenya    7          21            21
2       Tiger           Deer       Russia    3           9             9
3     Penguin           Fish  New Zealand    4          12            12
4       Panda         Bamboo        China    5          15            15

In [28]:
animal_data.head(5)

  Animal Name Favorite Foods      Country  Age  triple_Age  triple_Age_2
0      Monkey        Bananas        Egypt    2           6             6
1     Giraffe         Leaves        Kenya    7          21            21
2       Tiger           Deer       Russia    3           9             9
3     Penguin           Fish  New Zealand    4          12            12
4       Panda         Bamboo        China    5          15            15

In [30]:
#Create a list
Country_Region = {"Egypt":"North Africa",
                  "Kenya":"Africa",
                  "Russia":"Europe",
                  "New Zealand":"Oceania",
                  "China":"Asia"}

In [32]:
#Check the list
Country_Region

{'Egypt': 'North Africa',
 'Kenya': 'Africa',
 'Russia': 'Europe',
 'New Zealand': 'Oceania',
 'China': 'Asia'}

In [34]:
#Create a flag cloumn using lambda (deriving a variable)
animal_data['Region'] = animal_data['Country'].apply(lambda country: Country_Region.get(country))

In [36]:
#Check the dataframe
animal_data

,Animal Name,Favorite Foods,Country,Age,triple_Age,triple_Age_2,Region
0,Monkey,Bananas,Egypt,2,6,6,North Africa
1,Giraffe,Leaves,Kenya,7,21,21,Africa
2,Tiger,Deer,Russia,3,9,9,Europe
3,Penguin,Fish,New Zealand,4,12,12,Oceania
4,Panda,Bamboo,China,5,15,15,Asia

In [38]:
#Alternative way
#Create a flag cloumn using lambda (deriving a variable)
animal_data['Region_2'] = animal_data['Country'].apply(
    lambda country: (
        'North Africa' if country == 'Egypt' else
        'Africa' if country == 'Kenya' else
        'Oceania' if country == 'New Zealand' else
        'Asia' if country == 'China' else
        'Unknown'))

In [40]:
#Check the dataframe
animal_data

,Animal Name,Favorite Foods,Country,Age,triple_Age,triple_Age_2,Region,Region_2
0,Monkey,Bananas,Egypt,2,6,6,North Africa,North Africa
1,Giraffe,Leaves,Kenya,7,21,21,Africa,Africa
2,Tiger,Deer,Russia,3,9,9,Europe,Unknown
3,Penguin,Fish,New Zealand,4,12,12,Oceania,Oceania
4,Panda,Bamboo,China,5,15,15,Asia,Asia